<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Project Test Suite" tests="11" assertions="11" failures="0" errors="0" time="0.141195">
    <testsuite name="App\Tests\Controller\DefaultControllerTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Controller/DefaultControllerTest.php" tests="2" assertions="2" failures="0" errors="0" time="0.135150">
      <testcase name="testHomepageResponseCodeOkay" class="App\Tests\Controller\DefaultControllerTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Controller/DefaultControllerTest.php" line="10" assertions="1" time="0.119834"/>
      <testcase name="testHomepageContentContainsHelloWorld" class="App\Tests\Controller\DefaultControllerTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Controller/DefaultControllerTest.php" line="27" assertions="1" time="0.015316"/>
    </testsuite>
    <testsuite name="App\Test\SimpleTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/SimpleTest.php" tests="1" assertions="1" failures="0" errors="0" time="0.001371">
      <testcase name="testOnePlusOneEqualsTwo" class="App\Test\SimpleTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/SimpleTest.php" line="9" assertions="1" time="0.001371"/>
    </testsuite>
    <testsuite name="App\Util\Test\CalculatorTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Util/CalculatorTest.php" tests="8" assertions="8" failures="0" errors="0" time="0.004674">
      <testcase name="testCanCreateObject" class="App\Util\Test\CalculatorTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Util/CalculatorTest.php" line="10" assertions="1" time="0.001330"/>
      <testcase name="testAddOneAndOne" class="App\Util\Test\CalculatorTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Util/CalculatorTest.php" line="21" assertions="1" time="0.000542"/>
      <testsuite name="App\Util\Test\CalculatorTest::testAdditionsWithProvider" tests="3" assertions="3" failures="0" errors="0" time="0.000888">
        <testcase name="testAdditionsWithProvider with data set #0" assertions="1" time="0.000434"/>
        <testcase name="testAdditionsWithProvider with data set #1" assertions="1" time="0.000248"/>
        <testcase name="testAdditionsWithProvider with data set #2" assertions="1" time="0.000206"/>
      </testsuite>
      <testcase name="testDivideOneAndOne" class="App\Util\Test\CalculatorTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Util/CalculatorTest.php" line="60" assertions="1" time="0.000357"/>
      <testcase name="testDivideOneAndZero" class="App\Util\Test\CalculatorTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Util/CalculatorTest.php" line="76" assertions="1" time="0.000812"/>
      <testcase name="testDivideOneAndZeroAnnotation" class="App\Util\Test\CalculatorTest" file="/Users/matt/Library/Mobile Documents/com~apple~CloudDocs/11_Books/symfony/php-symfony4-book-codes/part-testing/test07_exceptions/tests/Util/CalculatorTest.php" line="96" assertions="1" time="0.000745"/>
    </testsuite>
  </testsuite>
</testsuites>
